Use scratch org names to find scratch orgs for deletion

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -77,7 +77,7 @@ deploy-scratch-org:
     - install_jq
     - authenticate $DEVHUB_AUTH_URL DEVHUB
     - assert_within_limits DEVHUB DailyScratchOrgs
-    - scratch_org_username=$(create_scratch_org DEVHUB)
+    - scratch_org_username=$(create_scratch_org DEVHUB "scratch/$CI_COMMIT_REF_SLUG")
     - scratch_org_auth_url=$(get_org_auth_url $scratch_org_username)
     - echo $scratch_org_username > SCRATCH_ORG_USERNAME.txt
     - echo $scratch_org_auth_url > SCRATCH_ORG_AUTH_URL.txt
@@ -148,8 +148,7 @@ delete-scratch-org:
     - install_salesforce_cli
     - install_jq
     - authenticate $DEVHUB_AUTH_URL DEVHUB
-    # - scratch_org_username=$(cat SCRATCH_ORG_USERNAME.txt)
-    # - delete_scratch_org DEVHUB $scratch_org_username
+    - delete_scratch_orgs DEVHUB "scratch/$CI_COMMIT_REF_SLUG"
   environment:
     name: scratch/$CI_COMMIT_REF_SLUG
     action: stop
@@ -659,6 +658,7 @@ deploy-to-production:
   # Create a scratch org.
   # Arguments:
   #     $1 = dev hub alias
+  #     $2 = org name for the scratch org
   # Returns the newly-created scratch org username.
 
   function create_scratch_org() {
@@ -666,7 +666,7 @@ deploy-to-production:
     local devhub_username=$1
     echo "devhub_username=$devhub_username" >&2
 
-    export local orgname="scratch/$CI_COMMIT_REF_SLUG"
+    export local orgname=$2
 
     # Create scratch org and grab its new username
     #local cmd="sfdx force:org:create --targetdevhubusername $devhub_username --setdefaultusername --definitionfile config/project-scratch-def.json --wait 10 --durationdays 30 --json" && (echo $cmd >&2)
@@ -680,10 +680,14 @@ deploy-to-production:
 
 
   # Get scratch org usernames
+  # Arguments:
+  #     $1 = org name for the scratch orgs
   # Returns one or more usernames (newline-separated)
 
   function get_scratch_org_usernames() {
-    export local orgname="scratch/$CI_COMMIT_REF_SLUG"
+
+    export local orgname=$1
+
     local usernames=$(sfdx force:org:list --json | jq -r ".result.scratchOrgs[] | select(.orgName==env.orgName) | .username")
     echo $usernames
   }
@@ -733,30 +737,36 @@ deploy-to-production:
   }
 
 
-  # Delete a scratch org.
+  # Delete all scratch orgs associated with a ref
   # Arguments
   #     $1 = dev hub username
-  #     $2 = scratch org username
+  #     $2 = ref name
 
-  function delete_scratch_org() {
+  function delete_scratch_orgs() {
 
     local devhub_username=$1
-    local scratch_org_username=$2
     echo "devhub_username=$devhub_username" >&2
-    echo "scratch_org_username=$scratch_org_username" >&2
 
     if [ ! $devhub_username ]; then
-      echo "ERROR No dev hub org username provided to 'delete_scratch_org' function" >&2
+      echo "ERROR No dev hub org username provided to 'delete_scratch_orgs' function" >&2
       exit 1;
     fi
 
-    if [ ! $scratch_org_username ]; then
-      echo "ERROR No scratch org username provided to 'delete_scratch_org' function" >&2
-      exit 1;
-    fi
+    local usernames=$(get_scratch_org_usernames $2)
 
-    local cmd="sfdx force:data:record:delete --sobjecttype ScratchOrgInfo --targetusername $devhub_username --where "'"SignupUsername='$scratch_org_username'"'" --json" && (echo $cmd >&2)
-    local output=$($cmd) && (echo $output | jq '.' >&2)
+    while read -r scratch_org_username; do
+
+      echo "scratch_org_username=$scratch_org_username" >&2
+
+      if [ ! $scratch_org_username ]; then
+        echo "ERROR No scratch org username provided to 'delete_scratch_orgs' function" >&2
+        exit 1;
+      fi
+
+      local cmd="sfdx force:data:record:delete --sobjecttype ScratchOrgInfo --targetusername $devhub_username --where "'"SignupUsername='$scratch_org_username'"'" --json" && (echo $cmd >&2)
+      local output=$($cmd) && (echo $output | jq '.' >&2)
+
+    done <<< "$usernames"
 
   }
 
