fix typos

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,7 +3,7 @@
 # We use nodejs, so a node image makes sense.
 # https://docs.gitlab.com/ee/ci/yaml/README.html#image
 ####################################################
-image: node:latest
+image: "node:latest"
 
 
 ####################################################
@@ -271,6 +271,87 @@ deploy-to-production:
   }
 
 
+  # Checks if there are LWC Jest Test files in any of the package directories of sfdx-project.json.
+  # This is necessary because npm will throw error if no test classes are found.
+  # No arguments.
+  # Returns `true` or `false`
+
+  function check_has_jest_tests() {
+    local hasJestTests=false
+    for pkgDir in $(jq -r '.packageDirectories[].path' < sfdx-project.json)
+    do
+      if [ -f $pkgDir ]; then
+        local fileCnt=$(find $pkgDir -type f -path "**/__tests__/*.test.js" | wc -l);
+        if [ $fileCnt -gt 0 ]; then
+          hasJestTests=true
+        fi
+      fi
+    done
+    echo $hasJestTests
+  }
+
+
+  # Runs `npm run test:lwc` to execute LWC Jest tests.
+  # Function takes no arguments.
+  # Should be called after `setup_lwc`.
+  # Uses `check_has_jest_tests` to know if there are actually any tests to run.
+  # If there aren't any jest tests then npm would throw an error and fail the job,
+  # so we skip running npm if there are no tests, essentially skipping them to avoid error.
+
+  function test_lwc_jest() {
+    local hasJestTests=$(check_has_jest_tests)
+    if [ $hasJestTests ]; then
+      npm run test:lwc
+    else
+      echo 'Skipping lwc tests, found no jest tests in any package directories' >&2
+    fi
+  }
+
+  # Function to run apex tests.
+  # We leverage the script property `test:apex` in package.json to provide developers a "hook"
+  # to control exactly how they want their apex test to be executed.
+  # Arguments:
+  #     $1 = org alias
+
+  function test_apex() {
+
+    local org_username=$1
+    echo "org_username=$org_username" >&2
+
+    if [ ! $org_username ]; then
+      echo "ERROR No org username provided to 'test_apex' function" >&2
+      exit 1;
+    fi
+
+    # Create a default package.json if file doesn't exist
+    if [ ! -f "package.json" ]; then
+      npm init -y
+    fi
+
+    # Check if the scripts property in package.json contains key for "test:apex"
+    local scriptValue=$(jq -r '.scripts["test:apex"]' < package.json)
+
+    # If no "test:apex" script property, then add one
+    if [ -n "$scriptValue" ]; then
+      local tmp=$(mktemp)
+      jq '.scripts["test:apex"]="sfdx force:apex:test:run --codecoverage --resultformat human --wait 10"' package.json > $tmp
+      mv $tmp package.json
+      echo "added test:apex script property to package.json" >&2
+      cat package.json >&2
+    fi
+
+    # Set the default username so any CLI commands
+    # the developer has set in their "test:apex" script in package.json
+    # will operate on the correct environment.
+    # Afterwards, restore the original default username, just in case it was different.
+    local old_org_username=$(jq -r '.result[].value' <<< $(sfdx force:config:get defaultusername --json))
+    sfdx force:config:set defaultusername=$org_username
+    npm run test:apex
+    sfdx force:config:set defaultusername=$old_org_username
+
+  }
+
+
   # Function to authenticate to Salesforce.
   # Don't expose the auth url to the logs.
   # Arguments:
@@ -334,7 +415,6 @@ deploy-to-production:
     export local package_name=$2
     echo "devhub_username=$devhub_username" >&2
     echo "package_name=$package_name" >&2
-    local output
 
     # Check environment variables
     if [ ! $package_name ]; then
@@ -364,8 +444,7 @@ deploy-to-production:
 
     # Retrieve package id for package name
     local cmd="sfdx force:package:list --targetdevhubusername \"$devhub_username\" --json" && (echo $cmd >&2)
-    output=$($cmd)
-    echo $output | jq >&2
+    local output=$($cmd) && (echo $output | jq >&2)
     package_id=$(jq -r '.result[] | select(.Name == env.package_name) | .Id' <<< $output)
     if [ ! $package_id ]; then
       echo "ERROR We could not find a package with name '$package_name' owned by this Dev Hub org." >&2
@@ -483,7 +562,7 @@ deploy-to-production:
     local package_version_id=$2
     echo "org_username=$org_username" >&2
     echo "package_version_id=$package_version_id" >&2
-    local cmd="sfdx force:package:install --targetusername "$org_username" --package $package_version_id --wait 10 --publishwait 10 --noprompt --json" && (echo $cmd >&2)
+    local cmd="sfdx force:package:install --targetusername $org_username --package $package_version_id --wait 10 --publishwait 10 --noprompt --json" && (echo $cmd >&2)
     local output=$($cmd) && (echo $output | jq >&2)
   }
 
@@ -598,7 +677,7 @@ deploy-to-production:
 
     local devhub_username=$1
     local scratch_org_username=$2
-    echo "devhub_username=$devhub_username" > &2
+    echo "devhub_username=$devhub_username" >&2
     echo "scratch_org_username=$scratch_org_username" >&2
 
     if [ ! $devhub_username ]; then
@@ -613,87 +692,6 @@ deploy-to-production:
 
     local cmd="sfdx force:data:record:delete --sobjecttype ScratchOrgInfo --targetusername $devhub_username --where "'"SignupUsername='$scratch_org_username'"'" --json" && (echo $cmd >&2)
     local output=$($cmd) && (echo $output | jq >&2)
-
-  }
-
-
-  # Checks if there are LWC Jest Test files in any of the package directories of sfdx-project.json.
-  # This is necessary because npm will throw error if no test classes are found.
-  # No arguments.
-  # Returns `true` or `false`
-
-  function check_has_jest_tests() {
-    local hasJestTests=false
-    for pkgDir in $(jq -r '.packageDirectories[].path' < sfdx-project.json)
-    do
-      if [ -f $pkgDir ]; then
-        local fileCnt=$(find $pkgDir -type f -path "**/__tests__/*.test.js" | wc -l);
-        if [ $fileCnt -gt 0 ]; then
-          hasJestTests=true
-        fi
-      fi
-    done
-    echo $hasJestTests
-  }
-
-
-  # Runs `npm run test:lwc` to execute LWC Jest tests.
-  # Function takes no arguments.
-  # Should be called after `setup_lwc`.
-  # Uses `check_has_jest_tests` to know if there are actually any tests to run.
-  # If there aren't any jest tests then npm would throw an error and fail the job,
-  # so we skip running npm if there are no tests, essentially skipping them to avoid error.
-
-  function test_lwc_jest() {
-    local hasJestTests=$(check_has_jest_tests)
-    if [ $hasJestTests ]; then
-      npm run test:lwc
-    else
-      echo 'Skipping lwc tests, found no jest tests in any package directories' >&2
-    fi
-  }
-
-  # Function to run apex tests.
-  # We leverage the script property `test:apex` in package.json to provide developers a "hook"
-  # to control exactly how they want their apex test to be executed.
-  # Arguments:
-  #     $1 = org alias
-
-  function test_apex() {
-
-    local org_username=$1
-    echo "org_username=$org_username" >&2
-
-    if [ ! $org_username ]; then
-      echo "ERROR No org username provided to 'test_apex' function" >&2
-      exit 1;
-    fi
-
-    # Create a default package.json if file doesn't exist
-    if [ ! -f "package.json" ]; then
-      npm init -y
-    fi
-
-    # Check if the scripts property in package.json contains key for "test:apex"
-    local scriptValue=$(jq -r '.scripts["test:apex"]' < package.json)
-
-    # If no "test:apex" script property, then add one
-    if [ -n "$scriptValue" ]; then
-      local tmp=$(mktemp)
-      jq '.scripts["test:apex"]="sfdx force:apex:test:run --codecoverage --resultformat human --wait 10"' package.json > $tmp
-      mv $tmp package.json
-      echo "added test:apex script property to package.json" >&2
-      cat package.json >&2
-    fi
-
-    # Set the default username so any CLI commands
-    # the developer has set in their "test:apex" script in package.json
-    # will operate on the correct environment.
-    # Afterwards, restore the original default username, just in case it was different.
-    local old_org_username=$(jq -r '.result[].value' <<< $(sfdx force:config:get defaultusername --json))
-    sfdx force:config:set defaultusername=$org_username
-    npm run test:apex
-    sfdx force:config:set defaultusername=$old_org_username
 
   }
 
