Back to commit-level scratch orgs

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -80,12 +80,12 @@ deploy-scratch-org:
   environment:
     name: scratch/$CI_COMMIT_REF_SLUG
     url: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_REF_NAME/raw/ENVIRONMENT.html?job=$CI_JOB_NAME
-    on_stop: delete-scratch-org
+    on_stop: delete-scratch-orgs
   artifacts:
     paths:
       - ENVIRONMENT.html
-
-
+      - SCRATCH_ORG_USERNAME.txt
+      - SCRATCH_ORG_AUTH_URL.txt
 
 
 ####################################################
@@ -110,8 +110,8 @@ test-scratch-apex:
       - $SCRATCH_DISABLED
       - $TEST_DISABLED
   allow_failure: false
-  # dependencies:
-  #   - deploy-scratch-org
+  dependencies:
+    - deploy-scratch-org
   script:
     - install_salesforce_cli
     - install_jq
@@ -123,9 +123,10 @@ test-scratch-apex:
 
 ####################################################
 # Deletes the scratch org.
+# Technically this deletes ALL the scratch orgs for the ref.
 # See https://docs.gitlab.com/ee/ci/environments.html#stopping-an-environment
 ####################################################
-delete-scratch-org:
+delete-scratch-orgs:
   stage: deploy-scratch
   only:
     variables:
@@ -339,20 +340,23 @@ deploy-to-production:
     fi
   }
 
+
   # Function to run apex tests.
   # We leverage the script property `test:apex` in package.json to provide developers a "hook"
   # to control exactly how they want their apex test to be executed.
   # Arguments:
-  #     $1 = devhub username or alias
+  #     $1 = username or alias of org to test
   #     $2 = org name property
+  # (Assumes you've already authorized to that org)
 
   function test_apex() {
-    local devhub=$1
-    local orgname=$2
-    local usernames=$(get_scratch_org_usernames $devhub $orgname)
-    if [ ! $usernames ]; then echo "There are no scratch orgs for $orgname"; exit 1; fi
-    local username=$(echo $usernames | awk '{print $1;}')
 
+    local org_username=$1
+
+    if [ ! $org_username ]; then
+      echo "ERROR No org username provided to 'test_apex' function" >&2
+      exit 1;
+    fi
 
     # Create a default package.json if file doesn't exist
     if [ ! -f "package.json" ]; then
@@ -376,7 +380,7 @@ deploy-to-production:
     # will operate on the correct environment.
     # Afterwards, restore the original default username, just in case it was different.
     local old_org_username=$(jq -r '.result[].value' <<< $(sfdx force:config:get defaultusername --json))
-    sfdx force:config:set defaultusername=$username
+    sfdx force:config:set defaultusername=$org_username
     npm run test:apex
     sfdx force:config:set defaultusername=$old_org_username
 
@@ -408,9 +412,11 @@ deploy-to-production:
 
   # Function to get SFDX Auth URL for an org.
   # Don't expose the force:org:display to logs to avoid exposing sensitive information like access tokens.
+  # Note this can only be run on a scratch org right after creating it, otherwise we won't be able to find the org
   # Arguments:
   #     $1 = target org alias whose auth url to get
   # Returns the SFDX Auth URL for the given org.
+  # TODO: Remove this? Functionality is included in the create function
 
   function get_org_auth_url() {
 
@@ -646,43 +652,49 @@ deploy-to-production:
   }
 
 
-  # Deploy to a scratch org, creating it first if necessary
+  # Create a scratch org and deploy to it.
   # Arguments:
   #     $1 = dev hub alias
   #     $2 = org name for the scratch org
-  # Returns the signin URL of the scratch org
+  # Populates artifacts for the username and the auth url
 
   function deploy_scratch_org() {
     local devhub=$1
     local orgname=$2
-    local usernames=$(get_scratch_org_usernames $devhub $orgname)
-    if [ ! $usernames ]; then
-      assert_within_limits $devhub DailyScratchOrgs
-      local username=$(create_scratch_org $devhub $orgname)
-      echo "Created scratch org $username"
-    else
-      local username=$(echo $usernames | awk '{print $1;}')
-    fi
-    auth_url=$(get_org_auth_url $username)
-    push_to_scratch_org $username
-    populate_url_artifact $username
+    assert_within_limits $devhub DailyScratchOrgs
+    local scratch_org_username=$(create_scratch_org $devhub $orgname)
+    echo $scratch_org_username > SCRATCH_ORG_USERNAME.txt
+    get_org_auth_url $scratch_org_username > SCRATCH_ORG_AUTH_URL.txt
+    push_to_scratch_org $scratch_org_username
+    populate_url_artifact $scratch_org_username
     echo "Deployed to scratch org $username for $orgname"
   }
 
 
 
-  # Create a scratch org.
+  # Create a new scratch org (i.e. if one doesn't exist yet)
   # Arguments:
   #     $1 = dev hub alias
   #     $2 = org name for the scratch org
+  # Populates the artifacts for username and auth url
   # Returns the newly-created scratch org username.
 
   function create_scratch_org() {
     local devhub=$1
     export local orgname=$2
+
+    # Create the scratch org
     local cmd="sfdx force:org:create --targetdevhubusername $devhub --wait 10 --durationdays 30 --json orgName=$orgname edition=Developer" && (echo $cmd >&2)
     local output=$($cmd) && (echo $output | jq '.' >&2)
     scratch_org_username="$(jq -r '.result.username' <<< $output)"
+    echo $scratch_org_username > SCRATCH_ORG_USERNAME.txt
+
+    # Get the auth URL
+    local cmd="sfdx force:org:display --verbose --targetusername $org_username --json" && (echo $cmd >&2)
+    local output=$($cmd)
+    org_auth_url="$(jq -r '.result.sfdxAuthUrl' <<< $output)"
+    echo $org_auth_url > SCRATCH_ORG_AUTH_URL.txt
+
     echo $scratch_org_username
   }
 
@@ -751,43 +763,14 @@ deploy-to-production:
   #     $2 = org name property of scratch orgs to delete
 
   function delete_scratch_orgs() {
-
-    echo "DELETE SCRATCH ORG"
-
-
-    echo "Delete scratch orgs"
-
     local devhub_username=$1
-    echo "devhub_username=$devhub_username" >&2
-
     local scratch_org_name=$2
-
-    if [ ! $devhub_username ]; then
-      echo "ERROR No dev hub org username provided to 'delete_scratch_orgs' function" >&2
-      exit 1;
-    fi
-
-    echo "Org names"
-    echo $2
     local usernames=$(get_scratch_org_usernames $devhub_username $scratch_org_name)
-
-    echo "Usernames"
-    echo $usernames
-
     for scratch_org_username in $usernames; do
-
-      echo "scratch_org_username=$scratch_org_username" >&2
-
-      if [ ! $scratch_org_username ]; then
-        echo "ERROR No scratch org username provided to 'delete_scratch_orgs' function" >&2
-        exit 1;
-      fi
-
+      echo "Deleting $scratch_org_username"
       local cmd="sfdx force:data:record:delete --sobjecttype ScratchOrgInfo --targetusername $devhub_username --where "'"SignupUsername='$scratch_org_username'"'" --json" && (echo $cmd >&2)
       local output=$($cmd) && (echo $output | jq '.' >&2)
-
     done
-
   }
 
 
