Update Salesforce.gitlab-ci.yml

diff --git a/Salesforce.gitlab-ci.yml b/Salesforce.gitlab-ci.yml
--- a/Salesforce.gitlab-ci.yml
+++ b/Salesforce.gitlab-ci.yml
@@ -184,13 +184,14 @@ create-package-version:
       - SUBSCRIBER_PACKAGE_VERSION_ID.txt
 
 ####################################################
-# Deploy into the sandbox org
+# Deploy a package into the sandbox org.
 ####################################################
-deploy-sandbox:
+deploy-sandbox-package:
   stage: staging
   only:
     variables:
       - $CI_COMMIT_REF_NAME == 'master'
+      - $USE_PACKAGES == 'true'
   except:
     variables:
       - $SANDBOX_DISABLED
@@ -205,21 +206,42 @@ deploy-sandbox:
     - install_salesforce_cli
     - install_jq
     - authenticate SANDBOX $SANDBOX_AUTH_URL
-    - 
     - package_version_id=$(cat SUBSCRIBER_PACKAGE_VERSION_ID.txt)
-
     - install_package_version SANDBOX $package_version_id
 
+####################################################
+# Deploy metadata into the sandbox org.
+####################################################
+deploy-sandbox-metadata:
+  stage: staging
+  only:
+    variables:
+      - $CI_COMMIT_REF_NAME == 'master'
+  except:
+    variables:
+      - $SANDBOX_DISABLED
+      - $USE_PACKAGES == 'true'
+  when: manual
+  allow_failure: false
+  environment:
+    name: sandbox
+    url: https://test.salesforce.com
+  script:
+    - install_salesforce_cli
+    - install_jq
+    - authenticate SANDBOX $SANDBOX_AUTH_URL
+    - deploy_metadata SANDBOX
 
 ####################################################
 # Promotes and installs the package version created
 # and installed in the sandbox in the prior stage.
 ####################################################
-deploy-production:
+deploy-production-package:
   stage: production
   only:
     variables:
       - $CI_COMMIT_REF_NAME == 'master'
+      - $USE_PACKAGES == 'true'
   except:
     variables:
       - $PRODUCTION_DISABLED
@@ -241,6 +263,28 @@ deploy-production:
     - authenticate PRODUCTION $PRODUCTION_AUTH_URL $DEVHUB_AUTH_URL
     - install_package_version PRODUCTION $package_version_id
 
+####################################################
+# Deploy metadata into the production org.
+####################################################
+deploy-production-metadata:
+  stage: production
+  only:
+    variables:
+      - $CI_COMMIT_REF_NAME == 'master'
+  except:
+    variables:
+      - $PRODUCTION_DISABLED
+      - $USE_PACKAGES == 'true'
+  when: manual
+  allow_failure: false
+  environment:
+    name: production
+    url: https://login.salesforce.com
+  script:
+    - install_salesforce_cli
+    - install_jq
+    - authenticate PRODUCTION $PRODUCTION_AUTH_URL $DEVHUB_AUTH_URL
+    - deploy_metadata PRODUCTION
 
 .sfdx_helpers: &sfdx_helpers |
 
@@ -498,18 +542,6 @@ deploy-production:
     fi
   }
 
-  # Generic Deploy function 
-  # Arguements: 
-  #     $1 = 
-  #     $2 =
-  #     $3 = 
-  # Executes the .....
-
-  function deploy_app() { 
-
-
-    
-  }
 
   # Function to get package name and ID.
   # Arguments:
@@ -848,6 +880,43 @@ deploy-production:
     done
   }
 
+  # Deploys metadata to the org.
+  # Arguments
+  #     $1 = org username to deploy to
+
+  function deploy_metadata() {
+
+    local org_username=$1
+
+    if [ ! $org_username ]; then
+      echo "ERROR No org username provided to 'deploy_metadata' function" >&2
+      exit 1;
+    fi
+
+    # Check for default package directory in sfdx-project.json
+    source_folder=$(cat sfdx-project.json | jq -r '.packageDirectories[] | select(.default==true) | .path')
+    if [ ! $source_folder ]; then
+      echo "no default package directory found, defaulting to first package directory listed in sfdx-project.json" >&2
+      cat sfdx-project.json >&2
+    fi
+
+    # Check for any package directory in sfdx-project.json
+    if [ ! $source_folder ]; then
+      echo "no default package directory found, defaulting to first package directory listed in sfdx-project.json" >&2
+      cat sfdx-project.json >&2
+      source_folder=$(cat sfdx-project.json | jq -r '.packageDirectories | .[0] | .path')
+    fi
+
+    # Giving up
+    if [ ! $source_folder ]; then
+      echo "ERROR Default package directory not specified. Specify a default package directory in sfdx-project.json." >&2
+      exit 1
+    fi
+
+    local cmd="sfdx force:source:deploy --targetusername $org_username --sourcepath $source_folder --wait 10 --json" && (echo $cmd >&2)
+    local output=$($cmd) && (echo $output | jq '.' >&2)
+
+  }
 
 before_script:
   - *sfdx_helpers
